name: My First Automated CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # STAGE 1: Automated Test Validation
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run Tests
      run: |
        pip install pytest
        pytest test_app.py

  # STAGE 2: Compile & Push to Docker Hub
  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          prakashgayathri/my-automated-flask-app:latest
          prakashgayathri/my-automated-flask-app:${{ github.sha }}

  # STAGE 3: Continuous Deployment (CD) to AWS Cluster
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-docker-image # <-- Strict chronological gateway block!
    steps:
    - name: Download and Configure Kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'

    - name: Check out repository code files
      uses: actions/checkout@v4 # <-- Required so the runner can see the flask-deployment.yaml file!

    - name: Authorize and Deploy Manifest to Cluster
      run: |
        kubectl config set-cluster staging-cluster --server=${{ secrets.KUBE_SERVER }} --insecure-skip-tls-verify=true
        kubectl config set-credentials github-actions --token=${{ secrets.KUBE_TOKEN }}
        kubectl config set-context staging-context --cluster=staging-cluster --user=github-actions
        kubectl config use-context staging-context

        echo "Dynamically injecting Commit SHA tag into manifest ..."
        sed -i "s/IMAGE_TAG/${{ github.sha }}/g" flask-deployment.yaml


        echo "Deploying application containers..."
        kubectl apply -f flask-deployment.yaml

