name: My First Automated CI Pipeline

# 1. The Trigger Event Rule
on:
  push:
    branches: [ "main" ]

# 2. The Task Execution Logic
jobs:
  build-and-test:
    runs-on: ubuntu-latest

 steps:
    - name: Step 1 - Check out repository code files
      uses: actions/checkout@v4

    - name: Step 2 - Install Python runtime
      uses: actions/setup-python@v5
      with:
        python-style: '3.10'

    - name: Step 3 - Execute automated pytest validations
      run: |
        python -m pytest test_app.py
